### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by poly000** [poly000/ash_meet_bot#2]
- [ ] support spaces in title
- [ ] support specify a duration, not 0s
- [ ] fix meet time on calendars
- [ ] persists meets arranged to disk, thus we could allow manage/edit/delete
- [ ] allow to set sets of time period that allow everyone to apply for meet
